name: crypto_wallet
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  aes_crypt_null_safe: ^2.0.2
  bip39: ^1.0.6
  bloc: ^8.0.3
  cryptography: ^2.0.5
  cryptography_flutter: ^2.0.2
  cs_ui:
    path: packages/cs_ui
  dotted_border: ^2.0.0+1
  ed25519_hd_key: ^2.2.0
  encrypt: ^5.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  flutter_bloc: ^8.0.1
  # flutter_localizations:
  #   sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^0.23.0+1
  hex: ^0.2.0
  http: ^1.1.0
  intl: ^0.17.0
  modal_bottom_sheet: ^3.0.0-pre  
  neumorphic_button: ^0.0.1+2
  pin_code_fields: ^7.4.0
  web3dart: ^2.3.5

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/abi/
    - assets/.env
    # - assets/.env.dev
